repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^k8s/.*\.yaml$
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml, --ignore-missing-imports]
        exclude: ^src/weave/|^tests/  # Exclude complex files with type issues

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        additional_dependencies: [pbr]
        args: [-r, src/]
        exclude: tests/|scripts/|demos/
