name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -e .[dev]
      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check .
          black --check .
          mypy --ignore-missing-imports src || true
      - name: Test
        run: |
          . .venv/bin/activate
          pip install pytest-cov
          pytest -q --cov=src --cov-report=term-missing --cov-fail-under=25
